# Generated by Django 5.2.7 on 2025-12-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='tipo_mantenimiento',
            field=models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo')], default='PREVENTIVO', max_length=50),
        ),
    ]
