# Generated by Django 5.2.7 on 2025-12-03 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_increase_rol_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('GUARDIA', 'Guardia'), ('MECANICO', 'Mecánico'), ('SUPERVISOR', 'Supervisor Zonal'), ('COORDINADOR_ZONA', 'Coordinador de Zona'), ('JEFE_TALLER', 'Jefe de Taller'), ('EJECUTIVO', 'Ejecutivo'), ('SPONSOR', 'Sponsor'), ('ADMIN', 'Administrador'), ('CHOFER', 'Chofer'), ('ADMINISTRATIVO_TALLER', 'Administrativo de Taller'), ('BODEGA', 'Bodega / Encargado de Repuestos')], default='ADMIN', max_length=25),
        ),
    ]
