# Generated by Django 5.2.7 on 2025-11-27 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0013_add_subido_por_to_evidencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='site',
        ),
    ]
