# Generated by Django 5.2.7 on 2025-12-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0014_remove_site_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='site',
            field=models.CharField(blank=True, help_text='Site o ubicación operativa donde se realiza la OT', max_length=100),
        ),
    ]
