# Generated by Django 5.2.7 on 2025-12-01 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0015_ordentrabajo_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='site',
        ),
    ]
