# Generated by Django 5.2.7 on 2025-11-27 05:16

import django.db.models.deletion
from django.db import migrations, models


def migrar_marcas_existentes(apps, schema_editor):
    """
    Migra las marcas existentes como texto a la tabla Marca.
    
    Este código se ejecuta DESPUÉS de crear la tabla Marca pero ANTES
    de cambiar el campo marca a ForeignKey.
    """
    Vehiculo = apps.get_model('vehicles', 'Vehiculo')
    Marca = apps.get_model('vehicles', 'Marca')
    
    # Obtener todas las marcas únicas existentes (excluyendo vacíos)
    marcas_texto = Vehiculo.objects.exclude(
        marca__isnull=True
    ).exclude(
        marca=''
    ).values_list('marca', flat=True).distinct()
    
    # Crear las marcas en la tabla
    marca_dict = {}
    for nombre_marca in marcas_texto:
        if nombre_marca and nombre_marca.strip():
            marca_nombre = nombre_marca.strip()
            marca, _ = Marca.objects.get_or_create(
                nombre=marca_nombre,
                defaults={'activa': True}
            )
            marca_dict[marca_nombre] = marca


def asociar_vehiculos_a_marcas(apps, schema_editor):
    """
    Asocia los vehículos con sus marcas correspondientes.
    
    Este código se ejecuta DESPUÉS de cambiar marca a ForeignKey.
    """
    Vehiculo = apps.get_model('vehicles', 'Vehiculo')
    Marca = apps.get_model('vehicles', 'Marca')
    
    # Necesitamos leer las marcas desde marca_temp
    # Pero como no podemos acceder al campo temporal después de la migración,
    # vamos a hacerlo de otra forma
    pass  # Esto se manejará en otra migración de datos separada


def revertir_migracion(apps, schema_editor):
    """
    Función de reversión (marcar marcas como no activas en lugar de eliminarlas).
    """
    Marca = apps.get_model('vehicles', 'Marca')
    Marca.objects.all().update(activa=False)


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_ingresovehiculo_fecha_salida_and_more'),
    ]

    operations = [
        # 1. Crear la tabla Marca primero
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, help_text='Nombre de la marca (ej: Toyota, Ford, Chevrolet)', max_length=64, unique=True)),
                ('activa', models.BooleanField(default=True, help_text='Indica si la marca está activa y puede ser usada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marca de Vehículo',
                'verbose_name_plural': 'Marcas de Vehículos',
                'ordering': ['nombre'],
            },
        ),
        # 2. Agregar índices a Marca
        migrations.AddIndex(
            model_name='marca',
            index=models.Index(fields=['nombre'], name='vehicles_ma_nombre_0a7695_idx'),
        ),
        migrations.AddIndex(
            model_name='marca',
            index=models.Index(fields=['activa'], name='vehicles_ma_activa_068bac_idx'),
        ),
        # 3. Agregar campo temporal marca_temp_id para almacenar el ID de la marca
        migrations.AddField(
            model_name='vehiculo',
            name='marca_temp_id',
            field=models.IntegerField(null=True, blank=True, help_text='Campo temporal para migración'),
        ),
        # 4. Migrar datos: crear marcas a partir de los valores existentes
        migrations.RunPython(migrar_marcas_existentes, reverse_code=revertir_migracion),
        # 5. Ahora necesitamos asociar los vehículos con las marcas
        # Primero creamos una función que asocia los vehículos
        migrations.RunPython(
            lambda apps, schema_editor: asociar_vehiculos_a_marcas_actual(apps, schema_editor),
            reverse_code=migrations.RunPython.noop
        ),
        # 6. Eliminar el índice antiguo antes de cambiar el tipo
        migrations.RemoveIndex(
            model_name='vehiculo',
            name='vehicles_ve_marca_45cd2d_idx',
        ),
        # 7. Eliminar el campo marca CharField
        migrations.RemoveField(
            model_name='vehiculo',
            name='marca',
        ),
        # 8. Crear el nuevo campo marca como ForeignKey
        migrations.AddField(
            model_name='vehiculo',
            name='marca',
            field=models.ForeignKey(blank=True, help_text='Marca del vehículo (validada contra tabla de marcas)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos', to='vehicles.marca'),
        ),
        # 9. Asociar vehículos con marcas usando marca_temp_id
        migrations.RunPython(
            lambda apps, schema_editor: asociar_vehiculos_desde_temp(apps, schema_editor),
            reverse_code=migrations.RunPython.noop
        ),
        # 10. Eliminar el campo temporal
        migrations.RemoveField(
            model_name='vehiculo',
            name='marca_temp_id',
        ),
        # 11. Crear nuevo índice compuesto (marca, modelo)
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['marca', 'modelo'], name='vehicles_ve_marca_i_c11f6b_idx'),
        ),
    ]


def asociar_vehiculos_a_marcas_actual(apps, schema_editor):
    """
    Asocia los vehículos actuales con sus marcas guardando el ID en marca_temp_id.
    """
    Vehiculo = apps.get_model('vehicles', 'Vehiculo')
    Marca = apps.get_model('vehicles', 'Marca')
    
    # Para cada vehículo, buscar su marca por nombre y guardar el ID
    for vehiculo in Vehiculo.objects.exclude(marca='').exclude(marca__isnull=True):
        if vehiculo.marca and vehiculo.marca.strip():
            try:
                marca_obj = Marca.objects.get(nombre=vehiculo.marca.strip())
                # Usar update directo en la base de datos para evitar problemas
                Vehiculo.objects.filter(id=vehiculo.id).update(marca_temp_id=marca_obj.id)
            except Marca.DoesNotExist:
                # Si no existe la marca, crear una nueva
                marca_obj = Marca.objects.create(
                    nombre=vehiculo.marca.strip(),
                    activa=True
                )
                Vehiculo.objects.filter(id=vehiculo.id).update(marca_temp_id=marca_obj.id)


def asociar_vehiculos_desde_temp(apps, schema_editor):
    """
    Asocia los vehículos con marcas usando marca_temp_id después de crear el ForeignKey.
    """
    Vehiculo = apps.get_model('vehicles', 'Vehiculo')
    Marca = apps.get_model('vehicles', 'Marca')
    
    # Para cada vehículo con marca_temp_id, asignar la marca
    for vehiculo in Vehiculo.objects.exclude(marca_temp_id__isnull=True):
        try:
            marca = Marca.objects.get(id=vehiculo.marca_temp_id)
            vehiculo.marca = marca
            vehiculo.save(update_fields=['marca'])
        except Marca.DoesNotExist:
            pass
