# Generated by Django 5.2.7 on 2025-11-27 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_marca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupvehiculo',
            name='site',
        ),
        migrations.RemoveField(
            model_name='historialvehiculo',
            name='site',
        ),
        migrations.RemoveField(
            model_name='vehiculo',
            name='site',
        ),
    ]
