# Generated by Django 5.2.7 on 2025-12-01 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_normalizar_patentes'),
        ('vehicles', '0008_remove_site_field'),
    ]

    operations = [
    ]
